version: '3'

services:
  # MySQL Service
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: htmx
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  # PHP Service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/html
      - ./includes:/var/www/includes
    ports:
      - "80:80"
    depends_on:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8001:80"
    depends_on:
      - database